### ISSUE TITLE
Bot Will Not Load

### ISSUE THREAD

**Issue by ShadowKA** [ShadowKA/AqilAcademy-bot#1]
With the current code in the [jsondev branch](https://github.com/ShadowKA/AqilAcademy-bot/tree/jsondev), the bot will not load.

**Comment by AqilCont** [comment]
hello

**Comment by SharkFinPro** [comment]
@ShadowKA 
Well...I just downloaded it, and tested for myself.
I tested on Shorky and it works fine.
I believe line 99 is the problem...as you need to set it as 'bot token here' to have it work...not some weird process stuff

**Comment by ShadowKA** [comment]
@SharkFinPro I have the bot logged in now. Did you get `.stats` to work?
