### ISSUE TITLE
The levels

### ISSUE THREAD

**Issue by AqilCont** [ShadowKA/AqilAcademy-bot#2]
There are a LOT of problems with the levels...
Some people have talked much and still haven't gained any XP
Also, when advancing to level 1, roles weren't given and i suspect thats the problem to EVERY role...
(This is constructive criticism. please don't take it negatively...)

**Comment by ShadowKA** [comment]
I'm now looking into any bugs that occurred earlier and working on fixing them.

**Comment by ShadowKA** [comment]
It appears that something is not working with the XP gain system, so I'll be looking into it.

**Comment by AqilCont** [comment]
:thonk: Okay

**Comment by ShadowKA** [comment]
**UPDATE**
Error has been found. There was an issue with preventing XP gain in the spam channel. I'm working on fixing it.

**Comment by ShadowKA** [comment]
It should be fixed now, a random number of XP between one and ten is given for each message that is posted outside of the #bots-plus-spam channel. @AqilCont is this good?

**Comment by AqilCont** [comment]
Yup :+1: 
Thanks for fixing it!
