### ISSUE TITLE
WHY DID YOU IGNORE MY LAST PULL REQUEST

### ISSUE THREAD

**Issue by AqilCont** [ShadowKA/AqilAcademy-bot#5]
I was REALLY hoping that something would be used of my work :rage:

**Comment by AqilCont** [comment]
This is the only way i know to comment...

**Comment by ShadowKA** [comment]
The last pull request was denied because there were no changes. (Your fork was a commit behind.) I've requested changes here: https://github.com/ShadowKA/AqilAcademy-bot/pull/4#pullrequestreview-71007744, please take a look.
